#!/usr/bin/env bash
#This script updates the package manager cache, installs nginx, stops the nginx service,
#modifies the nginx configuration file.

# update package manager cache
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo chmod -R 755 /var/www
sudo service nginx start

