#!/usr/bin/env bash
# A script that Installs and configure's HAproxy on your lb-01 server
sudo apt update -y
sudo apt install haproxy -y
echo "frontend main
	bind *:80
	mode http
	default_backend servers
backend servers
	balance roundrobin
	server web-01 54.234.95.185:80 check
	server web-02 100.26.138.32:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
