#!/usr/bin/env bash
# A bash script that Generates dumps for MYSQL and creates a compressed archive of it

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
