#!/usr/bin/env bash 
# A Bash script that loops from 1 to 10
# Display's bad luck for the 4th loop iteration
# Display's good luck for the 8th loop iteration
# Display's Best School for the other iterations

i=1
while ((i <= 10))
do
    if ((i != 4 && i != 8))
    then
        echo 'Best School'
    elif ((i == 4))
    then
        echo 'bad luck'
    else
        echo 'good luck'
    fi
	((i++))
done
