#!/usr/bin/env bash 

# A Bash script that loops from 1 to 10
# Display's bad luck for the 4th loop iteration
# Display's good luck for the 8th loop iteration
# Display's Best School for the other iterations

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
