#!/usr/bin/env bash

# A Bash script that displays the time for 12 hours and 59 minutes:
# Display hours from 0 to 12
# Display minutes from 1 to 59

count=0
while [ $count -le 12 ]
do
	echo "Hour: $count"
	minute=1
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		((minute++))
	done
	((count++))
done
