#!/usr/bin/bash
# A bash scrpit that installs ufw firewall and setup a few rules on web-01.

sudo apt-get install -y ufw
sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw status
yes | sudo ufw enable
sudo ufw status
