#!/usr/bin/env bash
#A bash script runs nginx as the user nginx listening on port 8080
sudo service nginx stop
chmod 644 /etc/nginx/nginx.conf
pkill -f apache2
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
